# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 349267325ce9db018632a6821f7796baed1a29a1f32f00ef5722260bf31147771610bf4f1118c874a163a4648996ca0aa7969144f89f2d2eeccd82993bfd3710

test:
  secret_key_base: c225056ad90a093e02b421addd070a8f7d0c161266954d6e84f5d8b78dd8ec8c906205d2cb4f2ad7b948668a3a722a2bac0328338859c7f912137a6ef382ff88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
